version: '3.8'
services:
  cache:
    image: valkey/valkey:8-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass leeloodallasmultipass
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
