apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: altinn-rettigheter-proxy
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://arbeidsgiver.dev.nav.no/altinn-rettigheter-proxy
    - https://arbeidsgiver.dev.intern.nav.no/altinn-rettigheter-proxy
    - https://altinn-rettigheter-proxy.dev.intern.nav.no/altinn-rettigheter-proxy
    - https://altinn-rettigheter-proxy.dev.nav.no/altinn-rettigheter-proxy
  liveness:
    path: /altinn-rettigheter-proxy/internal/alive
    initialDelay: 60
    timeout: 15
  readiness:
    path: /altinn-rettigheter-proxy/internal/ready
    initialDelay: 60
    timeout: 15
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/reportees"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: REDIS_HOST
      value: altinn-rettigheter-proxy-redis.arbeidsgiver.svc.cluster.local
    - name: CACHE_TIME_TO_LIVE_MILLIS
      value: "600000"
    - name: ALTINN_URL
      value: "https://tt02.altinn.no"
  envFrom:
    - configmap: loginservice-idporten
    - secret: altinn-rettigheter-proxy-redis-password
    - secret: altinn-rettigheter-proxy
  accessPolicy:
    inbound:
      rules:

        - application: klage-permittering-refusjon-api
          namespace: teamloennskomp
          cluster: dev-fss

        - application: permittering-refusjon-api
          namespace: teamloennskomp
          cluster: dev-fss

        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: min-side-arbeidsgiver-api
          namespace: fager

        - application: ia-tjenester-metrikker
        
        - application: notifikasjon-bruker-api
          namespace: fager

        - application: tiltak-refusjon-api

        - application: permitteringsskjema-api
          namespace: permittering-og-nedbemanning
          
        - application: innsyn-aareg-api
          namespace: fager
          cluster: dev-fss

    outbound:
      rules:
        - application: altinn-rettigheter-proxy-redis
  prometheus:
    enabled: true
    path:  /altinn-rettigheter-proxy/internal/actuator/prometheus

