apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: altinn-rettigheter-proxy
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://altinn-rettigheter-proxy.intern.dev.nav.no/altinn-rettigheter-proxy
  liveness:
    path: /altinn-rettigheter-proxy/internal/alive
    initialDelay: 60
    timeout: 15
  readiness:
    path: /altinn-rettigheter-proxy/internal/ready
    initialDelay: 60
    timeout: 15
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/reportees"
  redis:
    - instance: altinnrettigheter
      access: readwrite
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: CACHE_TIME_TO_LIVE_MILLIS
      value: "600000"
    - name: ALTINN_URL
      value: "https://tt02.altinn.no"
  envFrom:
    - secret: altinn-rettigheter-proxy-redis-password
    - secret: altinn-rettigheter-proxy
  accessPolicy:
    inbound:
      rules:
        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: min-side-arbeidsgiver-api
          namespace: fager

        - application: ia-tjenester-metrikker

        - application: notifikasjon-bruker-api
          namespace: fager

        - application: tiltak-refusjon-api

        - application: permitteringsskjema-api
          namespace: permittering-og-nedbemanning

        - application: permitteringsportal-api
          namespace: permittering-og-nedbemanning

        - application: aareg-innsyn-arbeidsgiver-api
          namespace: arbeidsforhold
          cluster: dev-fss

        - application: yrkesskade-melding-api
          namespace: yrkesskade

        - application: forebyggingsplan
          namespace: teamia

        - application: sosialhjelp-avtaler-api-dev
          namespace: teamdigisos

        - application: presenterte-kandidater-api
          namespace: toi

        - application: fia-arbeidsgiver
          namespace: pia

        - application: dsop-kontroll-q1
          namespace: dsopkontroll
          cluster: dev-fss

        - application: dsop-kontroll
          namespace: dsopkontroll
          cluster: dev-fss

        - application: institusjon-opphold-innrapportering-web
          namespace: team-rocket

    outbound:
      rules:
        - application: altinn-rettigheter-proxy-redis
      external:
        - host: tt02.altinn.no
  prometheus:
    enabled: true
    path:  /altinn-rettigheter-proxy/internal/actuator/prometheus

