apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: altinn-rettigheter-proxy
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://altinn-rettigheter-proxy.intern.dev.nav.no/altinn-rettigheter-proxy
  liveness:
    path: /altinn-rettigheter-proxy/internal/alive
  readiness:
    path: /altinn-rettigheter-proxy/internal/ready
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/reportees"
  valkey:
    - instance: altinnrettigheter
      access: readwrite
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: CACHE_TIME_TO_LIVE_MILLIS
      value: "600000"
    - name: ALTINN_URL
      value: "https://tt02.altinn.no"
  envFrom:
    - secret: altinn-rettigheter-proxy
  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp

        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: ia-tjenester-metrikker

        - application: tiltak-refusjon-api

        - application: aareg-innsyn-arbeidsgiver-api
          namespace: arbeidsforhold
          cluster: dev-fss

        - application: yrkesskade-melding-api
          namespace: yrkesskade

        - application: forebyggingsplan
          namespace: teamia

        - application: sosialhjelp-avtaler-api-dev
          namespace: teamdigisos

        - application: presenterte-kandidater-api
          namespace: toi

        - application: fia-arbeidsgiver
          namespace: pia

        - application: dsop-kontroll-q1
          namespace: dsopkontroll
          cluster: dev-fss

        - application: dsop-kontroll
          namespace: dsopkontroll
          cluster: dev-fss

        - application: fpinntektsmelding
          namespace: teamforeldrepenger

        - application: k9-inntektsmelding
          namespace: k9saksbehandling
    outbound:
      external:
        - host: tt02.altinn.no
  prometheus:
    enabled: true
    path:  /altinn-rettigheter-proxy/internal/actuator/prometheus

