apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: altinn-rettigheter-proxy
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/altinn-rettigheter-proxy/
  liveness:
    path: /altinn-rettigheter-proxy/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /altinn-rettigheter-proxy/internal/healthcheck
    initialDelay: 30
  vault:
    enabled: false
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
