apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: altinn-rettigheter-proxy
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  port: 8080
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      cpu: 5000m # https://home.robusta.dev/blog/stop-using-cpu-limits/
      memory: 1024Mi
  liveness:
    path: /altinn-rettigheter-proxy/internal/alive
  readiness:
    path: /altinn-rettigheter-proxy/internal/ready
  ingresses:
    - https://altinn-rettigheter-proxy.intern.nav.no/altinn-rettigheter-proxy/
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/reportees"
  redis:
    - instance: altinnrettigheter
      access: readwrite
  accessPolicy:
    inbound:
      rules:

        - application: sykefravarsstatistikk-api
          namespace: arbeidsgiver
          cluster: prod-fss

        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: prod-fss

        - application: ia-tjenester-metrikker

        - application: tiltak-refusjon-api

        - application: aareg-innsyn-arbeidsgiver-api
          namespace: arbeidsforhold
          cluster: prod-fss

        - application: sosialhjelp-avtaler-api
          namespace: teamdigisos

        - application: forebyggingsplan
          namespace: teamia

        - application: presenterte-kandidater-api
          namespace: toi
          
        - application: fia-arbeidsgiver
          namespace: pia         

        - application: dsop-kontroll
          namespace: dsopkontroll
          cluster: prod-fss

        - application: fpinntektsmelding
          namespace: teamforeldrepenger

    outbound:
      external:
        - host: www.altinn.no

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: CACHE_TIME_TO_LIVE_MILLIS
      value: "1800000"
    - name: ALTINN_URL
      value: "https://www.altinn.no/"
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"
  envFrom:
    - secret: altinn-rettigheter-proxy
  prometheus:
    enabled: true
    path: /altinn-rettigheter-proxy/internal/actuator/prometheus
